name: LOSAC
description: The Land of Smoke and Chariots - A Farragnarok Tower Defender
version: 2.2.0
homepage: https://github.com/FarragoFiction/LOSAC
author: paradoxLands

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  CommonLib:
    git: git://github.com/FarragoFiction/CommonLib.git
  LoaderLib:
    git: git://github.com/FarragoFiction/LoaderLib.git

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  build_config: any
